import random
import base64

def generate_dirt_texture():
    width = 16
    height = 16
    base_color = '#79553a'
    colors = ['#523a28', '#966c4a', '#6e5340']

    svg = f'<svg width="{width}" height="{height}" viewBox="0 0 {width} {height}" xmlns="http://www.w3.org/2000/svg" shape-rendering="crispEdges">'
    svg += f'<rect width="{width}" height="{height}" fill="{base_color}"/>'

    for y in range(height):
        for x in range(width):
            if random.random() > 0.2:
                color = random.choice(colors)
                svg += f'<rect x="{x}" y="{y}" width="1" height="1" fill="{color}"/>'

    svg += '</svg>'
    
    encoded_svg = base64.b64encode(svg.encode('utf-8')).decode('utf-8')
    data_uri = f'data:image/svg+xml;base64,{encoded_svg}'
    
    css_content = f"""/* Generated by scripts/generate_dirt_texture.py */
body {{
  background-image: url("{data_uri}");
  background-size: 64px;
  image-rendering: pixelated;
}}
"""
    return css_content

if __name__ == "__main__":
    css = generate_dirt_texture()
    print(css)
    
    # Optionally write to file directly if run from root
    try:
        with open("static/css/background.css", "w") as f:
            f.write(css)
        print("Successfully wrote to static/css/background.css")
    except FileNotFoundError:
        print("Could not write to static/css/background.css (directory not found?)")
